name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          ref: master
          path: theos/sdks

      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid
          
      - name: Setup iOS SDK
        run: |
          # Create symlink for the iOS 16.2 SDK (matches libplist version)
          sudo mkdir -p /opt/theos/sdks
          sudo ln -sf $PWD/theos/sdks/iPhoneOS16.2.sdk /opt/theos/sdks/iPhoneOS16.2.sdk
          
      - name: Build
        run: |
          export THEOS=theos
          export THEOS_DEVICE_IP=127.0.0.1
          export THEOS_DEVICE_PORT=22

          git submodule update --init
          
          # Clean existing libraries to force rebuild
          rm -rf lib/*.a
          bash get_libraries.sh
          
          # Show environment for debugging
          echo "THEOS: $THEOS"
          echo "SDK path: $(ls -la /opt/theos/sdks/)"
          
          # Build with verbose output to debug Swift compilation
          bash ipabuild.sh --debug

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: artifact
          path: build/*.ipa
