name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          ref: master
          path: theos/sdks

      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid
          
      - name: Setup iOS SDK
        run: |
          echo "=== SDK Setup ==="
          echo "Current directory: $(pwd)"
          echo "Available SDKs:"
          ls -la theos/sdks/
          
          # Use iOS 16.5 SDK (should exist)
          sudo mkdir -p /opt/theos/sdks
          sudo ln -sf $PWD/theos/sdks/iPhoneOS16.5.sdk /opt/theos/sdks/iPhoneOS16.5.sdk
          echo "SDK symlink created:"
          ls -la /opt/theos/sdks/
          
      - name: Build
        run: |
          echo "=== Build Setup ==="
          export THEOS=theos
          export THEOS_DEVICE_IP=127.0.0.1
          export THEOS_DEVICE_PORT=22

          echo "THEOS: $THEOS"
          echo "Current directory: $(pwd)"
          
          git submodule update --init
          
          echo "=== Library Setup ==="
          # Clean existing libraries to force rebuild
          rm -rf lib/*.a
          bash get_libraries.sh
          
          echo "=== Build Environment ==="
          echo "THEOS: $THEOS"
          echo "SDK path: $(ls -la /opt/theos/sdks/)"
          
          # Try building without debug first
          echo "=== Starting Build (Release Mode) ==="
          bash ipabuild.sh
          
          # If that fails, try debug mode
          if [ $? -ne 0 ]; then
            echo "=== Release build failed, trying debug mode ==="
            bash ipabuild.sh --debug
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: artifact
          path: build/*.ipa
